no more

diff --git a/.config/zsh/zsh-aliases b/.config/zsh/zsh-aliases
--- a/.config/zsh/zsh-aliases
+++ b/.config/zsh/zsh-aliases
@@ -7,22 +7,22 @@ alias l.='exa -a | egrep "^\."'
 
 ### navigation
 up() {
-  local d=""
-  local limit="$1"
-
-  # Default to limit of 1
-  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
-    limit=1
-  fi
-
-  for ((i=1;i<=limit;i++)); do
-    d="../$d"
-  done
-
-  # perform cd. Show error if cd fails
-  if ! cd "$d"; then
-    echo "Couldn't go up $limit dirs.";
-  fi
+    local d=""
+    local limit="$1"
+    
+    # Default to limit of 1
+    if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
+        limit=1
+    fi
+    
+    for ((i=1;i<=limit;i++)); do
+        d="../$d"
+    done
+    
+    # perform cd. Show error if cd fails
+    if ! cd "$d"; then
+        echo "Couldn't go up $limit dirs.";
+    fi
 }
 
 ### Confirm before overwriting something
